# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herenow', '0002_auto_20161101_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.CharField(default='No description', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='herenow.Location'),
        ),
    ]
